---
  - name: Install GitHub Bot
    copy:
      src: github-bot
      dest: /opt/ica0002/bin/github-bot
      mode: 0755

  - name: Configure GitHub bot
    copy:
      dest: /root/.github-api-token
      content: "{{ github_api_token }}\n"
      mode: 0600
