---
  - name: Install VM Admin
    copy:
      src: vm-admin.py
      dest: /usr/local/bin/vm-admin
      mode: 0755

  - name: Configure VM Admin
    copy:
      content: "{{ waldur_api_token }}\n"
      dest: /root/.waldur-api-token
      mode: 0600

  - name: Install VM SSH Key tool
    copy:
      src: vm-ssh-key.sh
      dest: /usr/local/bin/vm-ssh-key
      mode: 0755

  - name: Remove student VM manager -- use vm-admin instead
    file:
      path: /usr/local/bin/student-vms
      state: absent
