---
  - name: Install VM Admin
    copy:
      src: vm-admin.py
      dest: /usr/local/bin/vm-admin
      mode: 0755

  - name: Configure VM Admin
    copy:
      content: "{{ waldur_api_token }}\n"
      dest: /root/.waldur-api-token
      mode: 0600

  - name: Install VM SSH Key tool
    copy:
      src: vm-ssh-key.sh
      dest: /usr/local/bin/vm-ssh-key
      mode: 0755

  - name: Install student VM SSH manager
    copy:
      src: student-vms.sh
      dest: /usr/local/bin/student-vms
      mode: 0755
