github_api_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64356665333332303336356161636635386564303565376230653938663936323762373338376566
          3334373762343164363638666537353831646236626333300a616233336666616432306436396263
          36623463336537383561626664323633363032383336393735383332393566333265303438306263
          3635626663383032640a383762626538303664313339376138653561373337326534306263363066
          38663334343666356662633736343831356639633661306533626561613137356130313833303231
          3263346434633637333362366463363662336432333032306434
waldur_api_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39336235646663623032313332313762386562623665353461306661636239656337646561356163
          3665363464313765343366656361623961396535356539360a356161613237616638346532613139
          32646432356530383239363635353862656536626235396634633939313762376133383935396665
          3461636465333164630a303232646534376232656538333862616435623339366136653039343864
          38373931623839303733613539643064626662313666343133393533343439313265346230383362
          3437353534356235386264633334633163623363653661393530
