github_api_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64356665333332303336356161636635386564303565376230653938663936323762373338376566
          3334373762343164363638666537353831646236626333300a616233336666616432306436396263
          36623463336537383561626664323633363032383336393735383332393566333265303438306263
          3635626663383032640a383762626538303664313339376138653561373337326534306263363066
          38663334343666356662633736343831356639633661306533626561613137356130313833303231
          3263346434633637333362366463363662336432333032306434
openstack_api_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38653739633430653930313762613863333331373131363236306161663632333366353135313030
          6639306561633161313539333831643161343331343364610a643266383637666533383937643832
          62383661643238336564346339316438306236323230663763653837303832623463396632313136
          3566336232396264320a626234326665333663306538383235343135323934626163643531313364
          62303862336335383365643963623430366439626137613662343064623032663132663530353630
          3266653337633232316130663835636638613935623934323934
